name: ci

on:
  push:
    branches: main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Lint
        run: |
          deno --version
          deno task lint

      - name: Generate assets
        run: |
          deno task generate avatar > __avatar.svg
          deno task generate favicon > __favicon.svg
      
      - name: Check if assets up to date
        run: |
          diff __avatar.svg avatar.svg
          diff __favicon.svg favicon.svg
